### ISSUE TITLE
enhance the statistics panel

### ISSUE THREAD

**Issue by levg34** [levg34/baby-monitor#16]
The following enhancements would be interesting:

- [x] Move the statistics panel to a separate page (or hide/display with v-if) and add a button on the navbar
- [ ] Refresh when data is added
- [x] Select period of time for statistics: one week, one month, everything...
- [ ] Possibility to select a custom interval
