### ISSUE TITLE
statistics panel

### ISSUE THREAD

**Issue by levg34** [levg34/baby-monitor#3]
Add a statistics panel, with curves and a clear view of all useful data (drinks per day, etc).

- [ ] Reflect upon what data would be useful
- [ ] Reflect upon the way to show it
- [ ] Choose a library for the graphic display of curves, histograms and so on
- [ ] Add a link to the menu
- [ ] Make it work
