### ISSUE TITLE
requests from outside network

### ISSUE THREAD

**Issue by levg34** [levg34/baby-monitor#4]
From the inside network, the app works normally, but from outside the local network, all data must be read only and the add_something menus should dissapear.

Task list:
- [ ] Add a way to detect if the request comes from the local network or not
- [ ] Hide the menus if it is the case
- [ ] Block in the backend any forbidden action
